context: {}
package:

  name: magnettools
  version: 1.0.5
source:
  path: ./magnettools-1.0.5
 # git_url: https://github.com/feelpp/magnettools
 # git_rev: ba9af97951e000831e00911007da9abfd5d3b6f2
build:
  number: 0

Requirements:
  Build:
    - g++
    - cmake
    - swig
  run:
    - libgcc


